name: Build and Deploy Spring app to Aws

on:
  push:
    branches:
      - main # Set a branch to deploy

jobs:
  build-deploy:
    name: Build and Deploy Spring app to Aws
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_USERNAME }}/forvi:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secret.DOCKER_USERNAME}}
          password: ${{secret.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 # Use `uses` instead of `user`
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME }}/forvi:latest
          

